# Makefile.in generated by automake 1.10.2 from Makefile.am.
# cluster/Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008  Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.






pkgdatadir = $(datadir)/libra
pkglibdir = $(libdir)/libra
pkgincludedir = $(includedir)/libra
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
noinst_PROGRAMS = matrixTest$(EXEEXT) pointClusterTest$(EXEEXT)
subdir = cluster
DIST_COMMON = $(noinst_HEADERS) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/ac_detect_bluegene.m4 \
	$(top_srcdir)/m4/ac_inc_subst.m4 \
	$(top_srcdir)/m4/ac_lib_dwarf.m4 \
	$(top_srcdir)/m4/ac_lib_elf.m4 $(top_srcdir)/m4/ac_lib_papi.m4 \
	$(top_srcdir)/m4/ac_lib_subst.m4 \
	$(top_srcdir)/m4/ac_lib_xml2.m4 \
	$(top_srcdir)/m4/ac_paradyn_tools.m4 \
	$(top_srcdir)/m4/ac_pkg_swig.m4 $(top_srcdir)/m4/ac_pnmpi.m4 \
	$(top_srcdir)/m4/ac_python_devel.m4 \
	$(top_srcdir)/m4/ac_python_module.m4 \
	$(top_srcdir)/m4/ac_safe_check_lib.m4 \
	$(top_srcdir)/m4/ax_boost_base.m4 \
	$(top_srcdir)/m4/ax_prefix_config_h.m4 \
	$(top_srcdir)/m4/swig_enable_cxx.m4 \
	$(top_srcdir)/m4/swig_python.m4 $(top_srcdir)/m4/vtk.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = `echo $$p | sed -e 's|^.*/||'`;
am__installdirs = "$(DESTDIR)$(libdir)"
libLTLIBRARIES_INSTALL = $(INSTALL)
LTLIBRARIES = $(lib_LTLIBRARIES)
libcluster_la_LIBADD =
am_libcluster_la_OBJECTS = CLARA.lo ClusterDataSet.lo KMedoids.lo \
	Point.lo RNGenerator.lo ltqnorm.lo
libcluster_la_OBJECTS = $(am_libcluster_la_OBJECTS)
PROGRAMS = $(noinst_PROGRAMS)
am_matrixTest_OBJECTS = MatrixTest.$(OBJEXT)
matrixTest_OBJECTS = $(am_matrixTest_OBJECTS)
matrixTest_LDADD = $(LDADD)
matrixTest_DEPENDENCIES = libcluster.la
am_pointClusterTest_OBJECTS = PointClusterTest.$(OBJEXT)
pointClusterTest_OBJECTS = $(am_pointClusterTest_OBJECTS)
pointClusterTest_LDADD = $(LDADD)
pointClusterTest_DEPENDENCIES = libcluster.la
DEFAULT_INCLUDES = -I. -I$(top_builddir)
depcomp = $(SHELL) $(top_srcdir)/config/depcomp
am__depfiles_maybe = depfiles
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
SOURCES = $(libcluster_la_SOURCES) $(matrixTest_SOURCES) \
	$(pointClusterTest_SOURCES)
DIST_SOURCES = $(libcluster_la_SOURCES) $(matrixTest_SOURCES) \
	$(pointClusterTest_SOURCES)
HEADERS = $(noinst_HEADERS)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
ACLOCAL = ${SHELL} /home/tgamblin/src/libra/config/missing --run aclocal-1.10
AMTAR = ${SHELL} /home/tgamblin/src/libra/config/missing --run tar
AR = ar
AUTOCONF = ${SHELL} /home/tgamblin/src/libra/config/missing --run autoconf
AUTOHEADER = ${SHELL} /home/tgamblin/src/libra/config/missing --run autoheader
AUTOMAKE = ${SHELL} /home/tgamblin/src/libra/config/missing --run automake-1.10
AWK = gawk
BOOST_CPPFLAGS = -I/home/tgamblin/opt/boost/include/boost-1_34_1
BOOST_LDFLAGS = -L/home/tgamblin/opt/boost/lib
CC = mpiCC
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
COMMON_CPPFLAGS = -I/home/tgamblin/src/sw/include -I/home/tgamblin/opt/boost/include/boost-1_34_1
COMMON_LDFLAGS = -L/home/tgamblin/src/sw/x86_64-unknown-linux2.4/lib -lcommon  -L/home/tgamblin/opt/dwarf-20080615/lib -ldwarf -L/home/tgamblin/opt/dwarf-20080615/lib -lelf -L/home/tgamblin/src/sw/x86_64-unknown-linux2.4/lib -liberty
CPP = mpiCC -E
CPPFLAGS = 
CXX = mpiCC
CXXCPP = mpiCC -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2 -fno-omit-frame-pointer -DVTK_EXCLUDE_STRSTREAM_HEADERS
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DSYMUTIL = 
DWARF_LDFLAGS = -L/home/tgamblin/opt/dwarf-20080615/lib -ldwarf -L/home/tgamblin/opt/dwarf-20080615/lib -lelf
ECHO = echo
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
ELF_LDFLAGS = -L/home/tgamblin/opt/dwarf-20080615/lib -lelf
EXEEXT = 
F77 = g77
FC = mpif90
FCFLAGS = -g
FCLIBS =  -L/opt/local/encap/openmpi-1.2.6-intel/lib -lmpi_f90 -lmpi_f77 -lmpi -lopen-rte -lopen-pal -ldl -lnsl -lutil -L/opt/intel/fce/9.1.037/lib -L/usr/lib/gcc/x86_64-redhat-linux/3.4.5/ -L/usr/lib/gcc/x86_64-redhat-linux/3.4.5/../../../../lib64 -lsvml -lifport -lifcoremt -limf -lm -lipgo -lirc -lpthread -lirc_s
FFLAGS = -g -O2
GREP = /bin/grep
IBERTY_LDFLAGS = -L/home/tgamblin/src/sw/x86_64-unknown-linux2.4/lib -liberty
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = -lrt 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBTOOL_DEPS = config/ltmain.sh
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/tgamblin/src/libra/config/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
NMEDIT = 
OBJEXT = o
PACKAGE = libra
PACKAGE_BUGREPORT = 
PACKAGE_NAME = 
PACKAGE_STRING = 
PACKAGE_TARNAME = 
PACKAGE_VERSION = 
PAPI_CPPFLAGS = -I/opt/local/encap/papi-3.5.0/include
PAPI_LDFLAGS = -L/opt/local/encap/papi-3.5.0/lib64 -lpapi
PARADYN_CPPFLAGS = 
PATH_SEPARATOR = :
PMPI_INIT = pmpi_init_
PNMPI_CPPFLAGS = 
PNMPI_LDFLAGS = 
PNMPI_PATCH = 
PNMPI_WRAPPERGEN = 
PYTHON = /opt/rocks/bin/python2.4
PYTHON_CPPFLAGS = -I/opt/rocks/include/python2.4
PYTHON_EXEC_PREFIX = ${exec_prefix}
PYTHON_LDFLAGS = 
PYTHON_LIBS = -L/opt/rocks/lib -lpython2.4
PYTHON_PLATFORM = linux2
PYTHON_PREFIX = ${prefix}
PYTHON_VERSION = 2.4
RANLIB = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
SWIG = echo "Error: SWIG is not installed. You should look at http://www.swig.org" ; false -c++
SWIG_LIB = 
SWIG_PYTHON_CPPFLAGS = -I/opt/rocks/include/python2.4
SWIG_PYTHON_OPT = -python
SW_CPPFLAGS = -I/home/tgamblin/src/sw/include -I/home/tgamblin/opt/boost/include/boost-1_34_1
SW_LDFLAGS = -L/home/tgamblin/src/sw/x86_64-unknown-linux2.4/lib -lstackwalk -L/home/tgamblin/src/sw/x86_64-unknown-linux2.4/lib -lsymtabAPI -L/home/tgamblin/src/sw/x86_64-unknown-linux2.4/lib -lcommon  -L/home/tgamblin/opt/dwarf-20080615/lib -ldwarf -L/home/tgamblin/opt/dwarf-20080615/lib -lelf -L/home/tgamblin/src/sw/x86_64-unknown-linux2.4/lib -liberty
SYMTAB_CPPFLAGS = -I/home/tgamblin/src/sw/include -I/home/tgamblin/opt/boost/include/boost-1_34_1
SYMTAB_LDFLAGS = -L/home/tgamblin/src/sw/x86_64-unknown-linux2.4/lib -lsymtabAPI -L/home/tgamblin/src/sw/x86_64-unknown-linux2.4/lib -lcommon  -L/home/tgamblin/opt/dwarf-20080615/lib -ldwarf -L/home/tgamblin/opt/dwarf-20080615/lib -lelf -L/home/tgamblin/src/sw/x86_64-unknown-linux2.4/lib -liberty
VERSION = 0.9
VTK_CPPFLAGS = 
VTK_LIBS = 
VTK_WRAP_PYTHON = 
VTK_WRAP_PYTHON_INIT = 
XML2_LDFLAGS = 
abs_builddir = /home/tgamblin/src/libra/cluster
abs_srcdir = /home/tgamblin/src/libra/cluster
abs_top_builddir = /home/tgamblin/src/libra
abs_top_srcdir = /home/tgamblin/src/libra
ac_ct_CC = gcc
ac_ct_CXX = 
ac_ct_F77 = g77
ac_ct_FC = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = $(SHELL) /home/tgamblin/src/libra/config/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
pkgpyexecdir = /libra
pkgpythondir = /libra
pnmpidir = 
prefix = /home/tgamblin/opt/libra
program_transform_name = s,x,x,
psdir = ${docdir}
pyexecdir = ${prefix}/lib/python2.4/site-packages
pythondir = ${prefix}/lib/python2.4/site-packages
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = ../
top_builddir = ..
top_srcdir = ..
lib_LTLIBRARIES = libcluster.la
noinst_HEADERS = \
	CLARA.h \
	ClusterDataSet.h \
	Dissimilarity.h \
	hash.h \
	KMedoids.h \
	matrix.h \
	MersenneTwister.h \
	Point.h \
	RNGenerator.h \
	Stat.h \
	ltqnorm.h

libcluster_la_SOURCES = \
	CLARA.C \
	ClusterDataSet.C \
	KMedoids.C \
	Point.C \
	RNGenerator.C \
	ltqnorm.C

matrixTest_SOURCES = MatrixTest.C
pointClusterTest_SOURCES = PointClusterTest.C
LDADD = libcluster.la
all: all-am

.SUFFIXES:
.SUFFIXES: .C .lo .o .obj
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      ( cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh ) \
	        && { if test -f $@; then exit 0; else break; fi; }; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu  cluster/Makefile'; \
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  cluster/Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	test -z "$(libdir)" || $(MKDIR_P) "$(DESTDIR)$(libdir)"
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    f=$(am__strip_dir) \
	    echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(libLTLIBRARIES_INSTALL) $(INSTALL_STRIP_FLAG) '$$p' '$(DESTDIR)$(libdir)/$$f'"; \
	    $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(libLTLIBRARIES_INSTALL) $(INSTALL_STRIP_FLAG) "$$p" "$(DESTDIR)$(libdir)/$$f"; \
	  else :; fi; \
	done

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  p=$(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(libdir)/$$p'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(libdir)/$$p"; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  dir="`echo $$p | sed -e 's|/[^/]*$$||'`"; \
	  test "$$dir" != "$$p" || dir=.; \
	  echo "rm -f \"$${dir}/so_locations\""; \
	  rm -f "$${dir}/so_locations"; \
	done
libcluster.la: $(libcluster_la_OBJECTS) $(libcluster_la_DEPENDENCIES) 
	$(CXXLINK) -rpath $(libdir) $(libcluster_la_OBJECTS) $(libcluster_la_LIBADD) $(LIBS)

clean-noinstPROGRAMS:
	@list='$(noinst_PROGRAMS)'; for p in $$list; do \
	  f=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  echo " rm -f $$p $$f"; \
	  rm -f $$p $$f ; \
	done
matrixTest$(EXEEXT): $(matrixTest_OBJECTS) $(matrixTest_DEPENDENCIES) 
	@rm -f matrixTest$(EXEEXT)
	$(CXXLINK) $(matrixTest_OBJECTS) $(matrixTest_LDADD) $(LIBS)
pointClusterTest$(EXEEXT): $(pointClusterTest_OBJECTS) $(pointClusterTest_DEPENDENCIES) 
	@rm -f pointClusterTest$(EXEEXT)
	$(CXXLINK) $(pointClusterTest_OBJECTS) $(pointClusterTest_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/CLARA.Plo
include ./$(DEPDIR)/ClusterDataSet.Plo
include ./$(DEPDIR)/KMedoids.Plo
include ./$(DEPDIR)/MatrixTest.Po
include ./$(DEPDIR)/Point.Plo
include ./$(DEPDIR)/PointClusterTest.Po
include ./$(DEPDIR)/RNGenerator.Plo
include ./$(DEPDIR)/ltqnorm.Plo

.C.o:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.C.obj:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.C.lo:
	$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LTCXXCOMPILE) -c -o $@ $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	    $$tags $$unique; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(LTLIBRARIES) $(PROGRAMS) $(HEADERS)
installdirs:
	for dir in "$(DESTDIR)$(libdir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-libLTLIBRARIES clean-libtool \
	clean-noinstPROGRAMS mostlyclean-am

distclean: distclean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-exec-am: install-libLTLIBRARIES

install-html: install-html-am

install-info: install-info-am

install-man:

install-pdf: install-pdf-am

install-ps: install-ps-am

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-libLTLIBRARIES

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS all all-am check check-am clean clean-generic \
	clean-libLTLIBRARIES clean-libtool clean-noinstPROGRAMS ctags \
	distclean distclean-compile distclean-generic \
	distclean-libtool distclean-tags distdir dvi dvi-am html \
	html-am info info-am install install-am install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-libLTLIBRARIES install-man install-pdf \
	install-pdf-am install-ps install-ps-am install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags uninstall uninstall-am uninstall-libLTLIBRARIES

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
